# Generated by Django 4.2.3 on 2023-07-20 00:26

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Post",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255, verbose_name="Titulo")),
                ("slug", models.SlugField(max_length=255, unique=True)),
                ("content", models.TextField(verbose_name="Contenido")),
                ("author", models.TextField(verbose_name="autor")),
                ("created_on", models.DateTimeField(auto_now_add=True)),
                ("updated_on", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["created_on"],
            },
        ),
    ]
