# Generated by Django 4.2.3 on 2023-07-20 00:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("blogsite", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="slug",
            field=models.SlugField(blank=True, max_length=255, unique=True),
        ),
    ]
