# Generated by Django 4.2.3 on 2023-07-20 00:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("blogsite", "0002_alter_post_slug"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="title",
            field=models.CharField(max_length=254, verbose_name="Titulo"),
        ),
    ]
