# Generated by Django 4.2.3 on 2023-07-22 15:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Marca",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("nombre", models.CharField(max_length=255, verbose_name="Marca Auto")),
                (
                    "created",
                    models.DateField(
                        auto_now_add=True, verbose_name="Fecha de Creación"
                    ),
                ),
                (
                    "updated",
                    models.DateField(
                        auto_now=True, verbose_name="Fecha de Actualización"
                    ),
                ),
            ],
            options={
                "verbose_name": "marca",
                "verbose_name_plural": "marcas",
                "ordering": ["-created"],
            },
        ),
        migrations.CreateModel(
            name="ModeloAuto",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "nombre",
                    models.CharField(max_length=255, verbose_name="Modelo Auto"),
                ),
                (
                    "created",
                    models.DateField(
                        auto_now_add=True, verbose_name="Fecha de Creación"
                    ),
                ),
                (
                    "updated",
                    models.DateField(
                        auto_now=True, verbose_name="Fecha de Actualización"
                    ),
                ),
                (
                    "marca",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="relaciones.marca",
                        verbose_name="Marca auto",
                    ),
                ),
            ],
            options={
                "verbose_name": "modelo",
                "verbose_name_plural": "modelos",
                "ordering": ["-created"],
            },
        ),
    ]
