# Generated by Django 4.2.3 on 2023-07-25 01:11

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("relaciones", "0003_alter_tipocombustible_options_directorejecutivo"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="directorejecutivo",
            options={
                "ordering": ["-created"],
                "verbose_name": "director ejecutivo",
                "verbose_name_plural": "directores ejecutivos",
            },
        ),
    ]
