# Generated by Django 4.2.3 on 2023-07-28 00:10

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Empleado",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("emp_id", models.CharField(max_length=3, verbose_name=" ID")),
                ("emp_nombre", models.CharField(max_length=3, verbose_name="Nombre")),
                ("emp_correo", models.EmailField(max_length=254, verbose_name="Email")),
                (
                    "emp_designacion",
                    models.CharField(max_length=150, verbose_name="Designacion"),
                ),
                (
                    "created",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Fecha de Creación"
                    ),
                ),
                (
                    "update",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Fecha de Actualización"
                    ),
                ),
            ],
            options={
                "verbose_name": "empleado",
                "verbose_name_plural": "empleados",
                "db_table": "Employee",
                "ordering": ("emp_nombre", "-created"),
            },
        ),
    ]
