# Generated by Django 4.2.3 on 2023-07-28 01:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("crudapp", "0002_alter_empleado_emp_designacion"),
    ]

    operations = [
        migrations.AlterField(
            model_name="empleado",
            name="emp_nombre",
            field=models.CharField(max_length=255, verbose_name="Nombre"),
        ),
    ]
