# Generated by Django 4.2.3 on 2023-07-25 01:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("migraciones", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="preciohistoricovehiculos",
            options={
                "ordering": ["-created"],
                "verbose_name": "precio historico",
                "verbose_name_plural": "precios historicos",
            },
        ),
        migrations.AddField(
            model_name="preciohistoricovehiculos",
            name="color",
            field=models.CharField(
                default="Desconocido", max_length=150, verbose_name="Color"
            ),
        ),
        migrations.AlterField(
            model_name="preciohistoricovehiculos",
            name="modelo",
            field=models.TextField(),
        ),
    ]
