# Generated by Django 4.2.3 on 2023-07-25 01:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("migraciones", "0002_alter_preciohistoricovehiculos_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="preciohistoricovehiculos",
            name="color",
            field=models.CharField(
                default="Desconocido", max_length=50, verbose_name="Color"
            ),
        ),
    ]
